# Generated by Django 4.2.6 on 2024-12-19 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_test_end_date_alter_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 14, 2, 46, 250565, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
