# Generated by Django 4.2.6 on 2024-12-20 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 22, 12, 20, 8, 100197, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
