# Generated by Django 4.2.6 on 2024-12-22 15:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_test_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='variant')),
                ('is_true', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
            },
        ),
        migrations.RemoveField(
            model_name='checkquestion',
            name='checktest',
        ),
        migrations.RemoveField(
            model_name='checkquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='checktest',
            name='student',
        ),
        migrations.RemoveField(
            model_name='checktest',
            name='test',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_d',
        ),
        migrations.RemoveField(
            model_name='question',
            name='true_answer',
        ),
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 24, 15, 32, 9, 941759, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CheckQuestion',
        ),
        migrations.DeleteModel(
            name='CheckTest',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.question'),
        ),
    ]
