# Generated by Django 4.2.6 on 2024-12-22 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_answer_remove_checkquestion_checktest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=500, verbose_name='variant'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=500, verbose_name='savol'),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 24, 16, 40, 46, 795303, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
