# Generated by Django 4.2.6 on 2024-12-24 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_answer_answer_alter_question_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_true',
            field=models.BooleanField(default=False, verbose_name="to'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 15, 35, 29, 665978, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
