# Generated by Django 4.2.6 on 2024-12-24 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_answer_is_true_alter_test_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.question', verbose_name='savol'),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 16, 3, 26, 185978, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
