# Generated by Django 4.2.6 on 2024-12-26 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_answer_question_alter_test_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name="variantni o'chirish"),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 28, 9, 34, 20, 364430, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
