# Generated by Django 4.2.6 on 2024-12-27 08:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0020_answer_is_delete_alter_test_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration',
            field=models.PositiveIntegerField(default=20, verbose_name='test yechish vaqti'),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 8, 50, 12, 142479, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
        migrations.CreateModel(
            name='CheckTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='test ishlangan sana')),
                ('true_answers', models.PositiveIntegerField(default=0, verbose_name="to'g'ri javoblar soni")),
                ('percentage', models.PositiveBigIntegerField(default=0, verbose_name='foizi')),
                ('is_passed', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checktests', to='main.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_answer', models.CharField(max_length=500, verbose_name='berilgan javob')),
                ('is_true', models.BooleanField(default=False, verbose_name="to'g'riligi")),
                ('checktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.checktest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
        ),
    ]
