# Generated by Django 4.2.6 on 2024-12-28 08:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_test_duration_alter_test_end_date_checktest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_anonym',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkquestion',
            name='is_true',
            field=models.BooleanField(default=False, verbose_name="to'g'ri"),
        ),
        migrations.AlterField(
            model_name='checktest',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name="testdan o'tdi"),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 8, 11, 10, 666839, tzinfo=datetime.timezone.utc), verbose_name='tugash sanasi'),
        ),
    ]
