# Generated by Django 4.2.6 on 2025-02-16 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_answer_is_delete_alter_test_duration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checktest',
            options={'verbose_name': 'Natija', 'verbose_name_plural': 'Natijalar'},
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 18, 3, 39, 859466, tzinfo=datetime.timezone.utc), verbose_name='test tugash sanasi'),
        ),
        migrations.DeleteModel(
            name='CheckQuestion',
        ),
    ]
